trigger:
  branches:
    include:
      - main  # Trigger on changes to the main branch

pool:
  name: 'agentpool'  # Use the self-hosted agent pool or deployment group

variables:
  buildConfiguration: 'Release'
  nginxDeployPath: '/var/www/html/react'  # NGINX deployment directory

stages:
          - script: |
              npm install
              npm run build
            displayName: 'Install dependencies and build'

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.SourcesDirectory)/out'  # Path to build output
              ArtifactName: 'drop'
              publishLocation: 'Container'
