trigger:
  branches:
    include:
      - main  # Adjust this to match your branch name

pool:
  name: 'agentpool' 
  
steps:
  # Checkout the code from your repository
  - task: Checkout@2
    displayName: 'Checkout code'

  # Install Node.js
  - script: |
      # Ensure Node.js is installed on the self-hosted agent
      node -v
      npm -v
    displayName: 'Check Node.js and npm versions'

  # Install npm dependencies
  - script: |
      npm install
    displayName: 'Install npm dependencies'

  # Build the Next.js application
  - script: |
      npm run build
    displayName: 'Build Next.js app'

  - script: |
      echo "Deploying the app (if needed)"
      # Your deployment commands here, like SCP to a remote server or other deployment methods
    displayName: 'Deploy to production server'

  # Optionally, add post-deployment steps like testing or validation
