trigger:
  branches:
    include:
      - main  # Trigger on changes to the main branch

pool:
  name: 'agentpool'  # Use the self-hosted agent pool or deployment group

variables:
  buildConfiguration: 'Release'
  nginxDeployPath: '/var/www/html/react'  # NGINX deployment directory

stages:
  - stage: Build
    displayName: 'Build Stage'
    jobs:
      - job: Build_Job
        displayName: 'Build Job'
        steps:
          - task: UseNode@1
            inputs:
              version: '18.x'  # Specify Node.js version
            displayName: 'Use Node.js'

          - script: |
              npm install
              npm run build
            displayName: 'Install dependencies and build'

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.SourcesDirectory)/out'  # Path to build output
              ArtifactName: 'drop'
              publishLocation: 'Container'
