name: Deploy Next.js Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install  # Install the dependencies
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SECRET_KEY }}

      - name: Verify the app directory on the server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            # List the contents of the parent directory
            ls -la /var/www/html
          EOF
      - name: Deploy to Server via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            # Check if the directory exists before trying to cd into it
            if [ -d "/var/www/html/react-app" ]; then
              echo "Directory exists, proceeding with deployment"
              cd /var/www/html/react-app
            else
              echo "Directory does not exist, aborting deployment"
              exit 1
            fi
            # Pull the latest changes
            git pull origin main
            # Install dependencies (if needed)
            npm install
            # Build the app for production
            npm run build
            # Restart the app using PM2
            pm2 restart all || pm2 start npm --name "next-app" -- run start
          EOF
